### ISSUE TITLE
To f-string Or to Not f-string?

### ISSUE THREAD

**Issue by jacobseiler** [sage-home/sage-analysis#1]
I'm having a debate over whether I should implement f-strings into this plotting package.  On one hand, I truly think it increases the readability a lot and makes developing much easier.

However, implementing f-strings limits us to Python >=3.5.  Tbh I personally don't think this is TOO significant of a restriction, given the ubiquity of things such as virtual environments, but I still think it should be considered.

What are your feelings @manodeep ?

**Comment by manodeep** [comment]
@jacobseiler There are already a lot of print messages within the code-base - are you planning to change all of them to use `f-strings`? I am of the opinion that we should be consistent across the code-base. 

`python >= 3.5` is not too much of an ask - I am fine with that.

**Comment by jacobseiler** [comment]
If I go with f-strings, definitely going to update the print statements across the board.  

Duly noted, updating to f-strings, tally-ho!
