### ISSUE TITLE
Move calculation to where needed

### ISSUE THREAD

**Issue by manodeep** [sage-home/sage-analysis#10]
[These lines](https://github.com/sage-home/sage-analysis/blob/594e2dcca2f12b9f377500f690ffe1613013657b/sage_analysis/example_calcs.py#L44-L45) should only be executed when the `calc_sub_populations` flag is set. Otherwise, this calculation is performed and then potentially not needed.

**Comment by jacobseiler** [comment]
Fixed in latest pull into Master.
