### ISSUE TITLE
Plotting not working with Matplotlib version >= 3.5.2 (posibly earlier)

### ISSUE THREAD

**Issue by MarkMos** [sage-home/sage-analysis#15]
The plotting tools make use of the keyword `nonposy` which has been renamed `nonpositive` since Matplotlib 3.3.

This appears in example_plots.py lines 119, 204, 288, and 1355.

**Comment by manodeep** [comment]
Thanks Markus for the report. Do you mind opening a PR with the fix?

**Comment by manodeep** [comment]
This issue has been fixed with #16.
