### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by manodeep** [sage-home/sage-analysis#18]
The latest updates from #16 need to be incorporated into a new PyPI release. 

@jacobseiler While looking at updating the version in __version__.py, I see that that version says `0.1.2`, whereas the PyPI version says `0.2.2` - do you know how that happened? I checked that the `dev` branch (which is behind `master` now) also has the version set to `0.1.2`

@jacobseiler I am happy to update the version string to `0.2.3` and go on from there. Though you will still have to make the PyPI release since you are the owner

**Comment by manodeep** [comment]
@jacobseiler Do you have a second to check this out - there ~are two~ is one tasks:

~-  [ ] Identify the root cause for the discrepancy in the version between the repo (`0.1.2`) and PyPI (`0.2.2`). (Presumably, this requires merging in changes that are on your personal laptop and not pushed to the repo)~
-  [ ] Update version to `0.2.3` and make a new release on PyPI

Update: Only 1 task left

**Comment by jacobseiler** [comment]
@manodeep Hmmm I am honestly very unsure how that discrepancy arose...As you say, I must have been developing locally and for some reason published a new version without pushing to here (yucky, I know). 

Since the laptop that (presumably) has those changes is not with me anymore, let's just push a change to the current `master` that updates the version to `0.2.3` and then I'll release it?

**Comment by manodeep** [comment]
Sure thing - do you want me to update the version on the repo?

(Also, have you tried editing in the GitHub codespace - works great!)

**Comment by jacobseiler** [comment]
That would be helpful!

Oh yes, that's where you edit it directly and is useful for like One-liner changes that can be committed directly yes?

**Comment by manodeep** [comment]
It's a full-blown VSCode on the browser - an excellent tool (if you are already using VSCode)

I created the PR updated version in the version.py file. Are there any other places where the version needs to be updated?

**Comment by jacobseiler** [comment]
@manodeep I have published `0.2.3` to PyPi. What's your PyPi Username and I can add  you as a collaborator if you'd like to make releases as well (something we should be doing in the CI pipeline...)

And I've installed Linux on my work Windows machine so I'm still a filthy Vim user ;P

**Comment by manodeep** [comment]
@jacobseiler Hoorraay :)! That's a good idea about adding me as a collaborator - my PyPI username is manodeep. 

Get with the times - it's VSCode (and sometimes emacs) for me now

**Comment by jacobseiler** [comment]
Invite sent to add as a collaborator.

[You're living in the future with your fancy IDEs](https://www.youtube.com/watch?v=MDl4W3_6dqA)
