### ISSUE TITLE
requirements.txt missing on PyPI release

### ISSUE THREAD

**Issue by manodeep** [sage-home/sage-analysis#21]
Hey @jacobseiler - the `0.2.3` release on PyPI does not have the `requirements.txt` and that's causing the `sage-model` CI to fail. How did you generate the source distribution - my experience with Corrfunc has been through a MANIFEST.in file but that's not in the repo

**Comment by jacobseiler** [comment]
Oh that is very weird @manodeep.  I cloned `sage-analysis` from `master` and then did:

```bash
$ python setup.py sdist
$ twine upload dist/*
```

(Following https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56)

**Comment by manodeep** [comment]
@jacobseiler Can you create a new token on PyPI with project-scope and add that to the GitHub secrets (GitHub repo -> Settings -> Actions -> New Repo Secret)? I want to automate the PyPI publish process on GitHub Actions ([here](https://medium.com/@VersuS_/automate-pypi-releases-with-github-actions-4c5a9cfe947d))

**Comment by jacobseiler** [comment]
@manodeep Added `PYPI_PUBLISH` Repo Secret.

**Comment by manodeep** [comment]
The automatic PyPI uploader works now :) 

And as a side-effect, the sage-model tests also pass.
